id: P005375
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1CZ2429
  title: ཚད་མིན་བློའི་རྣམ་བཞག་།
  author: ''
  volumes:
    d0152073bfb74bc5aee175d421a711b5:
      image_group_id: I1CZ2480
      title: ''
      volume_number: 1
      total_pages: 240
      base_file: v001.txt
